### PR TITLE
 working on playlist model

### PR DESCRIPTION
**Pull request by jjamaltwin**
# Description
Added playlist model

## Type of change

Please delete options that are not relevant.
- [x] New feature (non-breaking change which adds functionality)

## Change Status
- [x] Complete, but not tested (may need new tests)

# How Has This Been Tested?
- [ ] Test A
- [ ] Test B

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My code has been reviewed by at least one peer
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] There are no merge conflicts

### CODE REVIEW

**Review by CampbellD84 — CHANGES_REQUESTED** [review]
It looks like there is a typo in the tracks section of the schema. Is "typa" suppose to be "type"? Besides that, the schema looks OK from what I can see.

**Review by CampbellD84 — COMMENTED** [review]
Fixes look good for the playlist model.

**Review by CampbellD84 — CHANGES_REQUESTED** [review]
Sorry, I missed this when I looked it over initially but in the User model, you need to import the ObjectId from mongoose  exactly like you did in the Playlist model. After that, I'll approve this.

**Comment by jjamaltwin** [comment]
ok,

**Comment by jjamaltwin** [comment]
Fixed it, thanks.

**Pull request merged**
